### ISSUE TITLE
"This event loop is already running" in jupyter notebook

### ISSUE THREAD

**Issue by bupticybee** [MountRouke/DerkGymIssues#4]
I follow the instructions in th website https://gym.derkgame.com/ and downloaded everything(or so I believe)

When I try to create a environment inside the jupyter notebook, I get the following error:

This event loop is already running

So my question is whether it's possible to use DerkGym inside jupyter notebook.

**Comment by FredrikNoren** [comment]
Hi!

Yes, it is. That error is because of the issue discussed here: https://github.com/googlecolab/colabtools/issues/1553

You can see a working example running on the CPU on Google Colab here: https://colab.research.google.com/drive/19lo2AxUCpoic4nRWIcBhbKRI33FfghLA, or for one (slightly more complicated to set up) GPU example here: https://colab.research.google.com/drive/1uIovS0NOSJc0nU_Yz7E1EMeXRu8cmxLl

**Comment by FredrikNoren** [comment]
Closing for now. Lmk if it's still a problem though

**Comment by RajK853** [comment]
I am getting this issue even after upgrading the `ipykernel` and `ipython` as mentioned in the above Google colab issue.

My jupyter notebook version is:
```
Selected Jupyter core packages...
IPython          : 7.31.1
ipykernel        : 6.8.0
ipywidgets       : 7.6.5
jupyter_client   : 7.0.6
jupyter_core     : 4.9.0
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.5.4
nbconvert        : 6.2.0
nbformat         : 5.1.3
notebook         : 6.4.5
qtconsole        : not installed
traitlets        : 5.1.1
``` 

In the past (a year ago), I had it working in my notebook. Today while I was trying to play around with the old codes, I am getting this issue while creating the GymDerk environment using the command:
```python
from gym_derk.envs import DerkEnv

env = DerkEnv()
```
